In [2]:
import pandas as pd

In [25]:
import io

data = """
Order_ID,Order_Date,Customer_ID,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Payment_Method
1001,2024-01-15,CUST-882,North,Electronics,Wireless Mouse,2,25.50,0.0,Credit Card
1002,2024-01-16,CUST-411,West,Furniture,Office Chair,1,150.00,0.1,PayPal
1003,2024-01-18,CUST-905,East,Electronics,USB Cable,5,8.99,0.0,Credit Card
1004,2024-01-20,CUST-112,South,Office Supplies,Notebook 3-Pack,3,12.00,0.05,Credit Card
1005,2024-01-21,CUST-882,North,Electronics,Wireless Mouse,1,25.50,0.0,Debit Card
1006,2024-01-25,CUST-654,West,Furniture,Desk Lamp,2,45.00,0.15,Cash
1007,2024-01-28,CUST-331,East,Electronics,27-inch Monitor,1,299.99,0.0,Credit Card
1008,2024-02-01,CUST-905,East,Office Supplies,Gel Pens 10-Pack,10,5.50,0.0,PayPal
1009,2024-02-03,CUST-204,South,Furniture,Office Chair,4,150.00,0.2,Credit Card
1010,2024-02-05,CUST-771,North,Electronics,Mechanical Keyboard,1,85.00,0.0,Debit Card
1011,2024-02-10,CUST-112,South,Office Supplies,,2,15.00,0.0,Credit Card
1012,2024-02-12,CUST-559,West,Electronics,Wireless Mouse,3,25.50,0.05,PayPal
1013,2024-02-15,CUST-882,North,Furniture,Standing Desk,1,450.00,0.1,Credit Card
1014,2024-02-18,CUST-331,East,Electronics,USB Cable,2,8.99,0.0,Debit Card
1015,2024-02-22,CUST-411,West,Office Supplies,Stapler,1,11.25,0.0,Cash
"""

df = pd.read_csv(io.StringIO(data.strip()))

# Convert Order_Date to proper datetime format
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [26]:
df

,Order_ID,Order_Date,Customer_ID,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Payment_Method
0,1001,2024-01-15,CUST-882,North,Electronics,Wireless Mouse,2,25.50,0.00,Credit Card
1,1002,2024-01-16,CUST-411,West,Furniture,Office Chair,1,150.00,0.10,PayPal
2,1003,2024-01-18,CUST-905,East,Electronics,USB Cable,5,8.99,0.00,Credit Card
3,1004,2024-01-20,CUST-112,South,Office Supplies,Notebook 3-Pack,3,12.00,0.05,Credit Card
4,1005,2024-01-21,CUST-882,North,Electronics,Wireless Mouse,1,25.50,0.00,Debit Card
5,1006,2024-01-25,CUST-654,West,Furniture,Desk Lamp,2,45.00,0.15,Cash
6,1007,2024-01-28,CUST-331,East,Electronics,27-inch Monitor,1,299.99,0.00,Credit Card
7,1008,2024-02-01,CUST-905,East,Office Supplies,Gel Pens 10-Pack,10,5.50,0.00,PayPal
8,1009,2024-02-03,CUST-204,South,Furniture,Office Chair,4,150.00,0.20,Credit Card
9,1010,2024-02-05,CUST-771,North,Electronics,Mechanical Keyboard,1,85.00,0.00,Debit Card
10,1011,2024-02-10,CUST-112,South,Office Supplies,NaN,2,15.00,0.00,Credit Card
11,1012,2024-02-12,CUST-559,West,Electronics,Wireless Mouse,3,25.50,0.05,PayPal
12,1013,2024-02-15,CUST-882,North,Furniture,Standing Desk,1,450.00,0.10,Credit Card
13,1014,2024-02-18,CUST-331,East,Electronics,USB Cable,2,8.99,0.00,Debit Card
14,1015,2024-02-22,CUST-411,West,Office Supplies,Stapler,1,11.25,0.00,Cash

In [5]:
df.columns = df.columns.str.lower()

In [7]:
df

,order_id,order_date,customer_id,region,product_category,product_name,quantity,unit_price,discount,payment_method
0,1001,2024-01-15,CUST-882,North,Electronics,Wireless Mouse,2,25.50,0.00,Credit Card
1,1002,2024-01-16,CUST-411,West,Furniture,Office Chair,1,150.00,0.10,PayPal
2,1003,2024-01-18,CUST-905,East,Electronics,USB Cable,5,8.99,0.00,Credit Card
3,1004,2024-01-20,CUST-112,South,Office Supplies,Notebook 3-Pack,3,12.00,0.05,Credit Card
4,1005,2024-01-21,CUST-882,North,Electronics,Wireless Mouse,1,25.50,0.00,Debit Card
5,1006,2024-01-25,CUST-654,West,Furniture,Desk Lamp,2,45.00,0.15,Cash
6,1007,2024-01-28,CUST-331,East,Electronics,27-inch Monitor,1,299.99,0.00,Credit Card
7,1008,2024-02-01,CUST-905,East,Office Supplies,Gel Pens 10-Pack,10,5.50,0.00,PayPal
8,1009,2024-02-03,CUST-204,South,Furniture,Office Chair,4,150.00,0.20,Credit Card
9,1010,2024-02-05,CUST-771,North,Electronics,Mechanical Keyboard,1,85.00,0.00,Debit Card
10,1011,2024-02-10,CUST-112,South,Office Supplies,NaN,2,15.00,0.00,Credit Card
11,1012,2024-02-12,CUST-559,West,Electronics,Wireless Mouse,3,25.50,0.05,PayPal
12,1013,2024-02-15,CUST-882,North,Furniture,Standing Desk,1,450.00,0.10,Credit Card
13,1014,2024-02-18,CUST-331,East,Electronics,USB Cable,2,8.99,0.00,Debit Card
14,1015,2024-02-22,CUST-411,West,Office Supplies,Stapler,1,11.25,0.00,Cash

In [ ]:
df[(df['unit_price'] == 25) & (df['region'] == 'North')]

KeyError: 'unit_price'